[[redirects]]
    from="/version/1-1-0/*"
    to="https://1-1-0.netlify-se-test.com/:splat"
    force=true
    status=200

    [[redirects]]
    from="/version/1-1-0"
    to="https://1-1-0.netlify-se-test.com"
    force=true
    status=200